### ISSUE TITLE
Exception in saveAnomaliesAnalyzed when saving

### ISSUE THREAD

**Issue by othermusketeer** [theSpeare/RoverScience-Revisit#17]
An exception is preventing all types of saves (persistent, quicksave, and autosave). I've had it happen in multiple scenes, each NOT having the rover science part. In one scene there were not any wheels of any kind loaded in physics range. I have not even used the part yet. The only unloaded rover I have was made long before installing the mod.

Unfortunately, I restarted the game already and do not have the full log. I just have the related section I google'd.

If I try loading the mod again, I will try to get a full log.

`[LOG 19:22:33.354] Attempting to save anomalies analyzed
[EXC 19:22:33.357] NullReferenceException: Object reference not set to an instance of an object
    RoverScience.RoverScienceScenario.saveAnomaliesAnalyzed (.ConfigNode node)
    RoverScience.RoverScienceScenario.OnSave (.ConfigNode node)
    ScenarioModule.Save (.ConfigNode node)
    ProtoScenarioModule..ctor (.ScenarioModule module)
    ScenarioRunner.GetUpdatedProtoModules ()
    Game.Updated ()
    QuickSaveLoad.doSave (System.String filename)
    QuickSaveLoad.quickSave (Boolean saveAs)
    QuickSaveLoad.Update ()`

**Comment by theSpeare** [comment]
Oh damn it I know exactly what's wrong but I'm currently out of the house for the day. I DID bring my laptop though so I might be able to push a fix really quickly.

Was this for the KSP 1.2 build or the KSP 1.1.3?

Thank you for the detailed report.

**Comment by othermusketeer** [comment]
My appologies. I am running KSP x64 1.1.3. The mod is not in an isolated enviroment, as I have >150 mods installed (mostly small part mods).

**Comment by theSpeare** [comment]
Thanks again for the report. This should be fixed now as of 2.1.3; it took me far too long to do it because I had to do some (very stupid) merging and re-writing. I will keep this issue open until it is verified that the exception is no longer thrown.

**Comment by othermusketeer** [comment]
Im baby-sitting my niece-in-law right now, but i will try it out later
tonight when im home. Probably after 9pm. (Gotta watch Big Bang Theory
first)
