### ISSUE TITLE
Check for nearby anomalies

### ISSUE THREAD

**Issue by theSpeare** [theSpeare/RoverScience-Revisit#7]
> Side question - do you get (significantly) more science near Munoliths and the like? That might be something to check for as well

@etmoonshade KSPForums

**Comment by theSpeare** [comment]
will need coordinates of all anomalies.

need to store these coordinates and also store if the anomalies have been studied before (and if so, prevent them from spawning as science spots

**Comment by etmoonshade** [comment]
Thaaaaaat's why I got that e-mail. I see now. :V

**Comment by theSpeare** [comment]
all (most) anomalies long/lat coordinates have been added and placed into Anomalies.cfg. I've also written a method to load in these values into a dictionary:

```
Key: planetName
Value: list of class Anomaly (which contains id, long/lat, name)
_this shall be later used for implementation of checking nearby anomalies, generating spots at the anomalies and saving "analyzed"_
```

**ensure that anomalies have a bonus and are guaranteed when nearby (will need to write a function to check for nearby anomalies**

**Comment by theSpeare** [comment]
successfully detecting anomalies and creating dedicated science spots at location. Most functions have been revised to allow specific long/lat coords for science spots, and anomaly checking. Anomalies will now provide a hard 300 science (with a small chance of 500).

Still need to check if player has already analyzed near an anomaly (and to give a warning that you will no longer get that anomaly).
- make it so that you don't generate the spot at the anomaly at all
- check for id

**Comment by theSpeare** [comment]
works now!
- will no longer add anomaly id to completedlist when analyzing
- will no longer create anomalySpot if it's already been analyzed
- everything saves to persistence/quicksave
